### ISSUE TITLE
I have seen some bugs

### ISSUE THREAD

**Issue by ffilz** [pgorman/travellercharactergenerator#1]
I have seen some bugs/issues, also I'd love to extend this.

Would you be interested in re-licensing with GPL or another open license to make it more clear?

Frank

**Comment by pgorman** [comment]
It's already licensed under the more permissive two-clause BSD license.

Feel free to hack on it. If you find bugs, I'd appreciate a patch or pull request.

Thanks.

**Comment by ffilz** [comment]
Ah, cool. I'll be submitting a pull request soon. This is where I'm at right now:

I'm working on fixing the code. Errors I've fixed so far:
Drafted - don't check for commission on first term
Scouts - generator gave 3 skills at 1st term, fixed to 2
Merchants - moved Pilot-1 from Rank 1 to Rank 4
Mustering out - it turns out it was giving an extra mustering out roll to cash, so you got terms + (0-3) + 1 with up to 4 cash rolls
Mustering out - when granted a gun or blade, it gives you a weapon first, then skills after, if you already have a skill, it gives you the weapon for the first skill granted
Mustering out: fixed Gambling OR Rank 5+ gave +1 to both material and cash benefits rolls
Retirement pay - skip this for scouts and other

Any other bugs (the vehicle skill issue will be covered by a URL parameter)?

I'm also adding a URL parameter to control the service history verbosity from none, original, and verbose (show all the rolls). This helps immensely in testing, and I like seeing it for generated characters.

I also plan to add URL parameters to select which skill tables to use (1977, 1981, The Traveller Book). There might also be a strict 1977 option (removes the 3rd bonus mustering out benefit for Rank 5+).

Other options I have in mind:
Indicate preferred service
Preferred service selection strategies (the code just looks at enlistment, some might care more about survival, commission, or promotion)
Mustering out strategies (at least one to try to get a ship first instead of cash first)
Maybe other strategies

It would also be cool to add the Supplement 4 careers. On the other hand, I like the idea of those being a bonus for players willing to get out their books and dice (or prevail on me to do so on their behalf).

**Comment by ffilz** [comment]
PR submitted

**Comment by pgorman** [comment]
Thanks! Merged. I also clarified the license in the README.

**Comment by ffilz** [comment]
Cool, though bummer you already merged, someone found a couple issues that I messed up. Will have another PR tomorrow...
